{
 "title": "Antidote",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(antidote_open_transactions, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "description": "Antidote errors which need investigation in the logging logs",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "antidote_error_count{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "description": "Antidote warnings which need investigation in the logging logs rather sooner than later.\nThis graph will decay over time.\nIf the warning count keeps increases, this indicates that the node might crash soon.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(antidote_warning_count{instance=\"$node\"}[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DC Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "antidote_dc_count{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Antidote API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "txns/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_transaction{type=\"aborted\",instance=\"$node\"}[1m])",
       "legendFormat": "Aborted Transactions Rate"
      },
      {
       "expr": "irate(antidote_transaction{type=\"open\",instance=\"$node\"}[1m])",
       "legendFormat": "Open Transactions Rate"
      },
      {
       "expr": "antidote_transaction{type=\"open\",instance=\"$node\"}",
       "legendFormat": "Open Transactions"
      },
      {
       "expr": "antidote_transaction{type=\"aborted\",instance=\"$node\"}",
       "legendFormat": "Aborted Transactions Total"
      },
      {
       "expr": "antidote_transaction{type=\"finished\",instance=\"$node\"}",
       "legendFormat": "Finished Transactions Total"
      }
     ]
    },
    {
     "title": "Operations Client",
     "type": "graph",
     "description": "Updates, Reads, Reads (asynchronous)\nRate & Total",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_operations_total{instance=\"$node\"}[1m])",
       "legendFormat": "{{type}} rate"
      },
      {
       "expr": "antidote_operations_total{instance=\"$node\"}",
       "legendFormat": "{{type}} total"
      }
     ]
    },
    {
     "title": "Operations Internal",
     "type": "graph",
     "description": "Reads, Reads(async) internal",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_operations_internal_total{instance=\"$node\"}[1m])",
       "legendFormat": "{{type}} rate"
      },
      {
       "expr": "antidote_operations_internal_total{instance=\"$node\"}",
       "legendFormat": "{{type}} total"
      }
     ]
    },
    {
     "title": "Operations DC Communication",
     "type": "graph",
     "description": "Reads, Reads(async) internal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_dc_ops_received{instance=\"$node\"}[1m])",
       "legendFormat": "Ops received rate"
      },
      {
       "expr": "antidote_dc_ops_received{instance=\"$node\"}",
       "legendFormat": "Ops received total"
      }
     ]
    },
    {
     "title": "Operations DC Communication Size",
     "type": "graph",
     "description": "Reads, Reads(async) internal",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes", "label": "size/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_dc_ops_received_size{instance=\"$node\"}[1m])",
       "legendFormat": "Ops received rate"
      },
      {
       "expr": "antidote_dc_ops_received_size{instance=\"$node\"}",
       "legendFormat": "Ops received total"
      }
     ]
    },
    {
     "title": "Staleness",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "  rate(antidote_staleness_sum{instance=\"$node\"}[5m])\n/\n  rate(antidote_staleness_count{instance=\"$node\"}[5m])",
       "legendFormat": "Staleness"
      }
     ]
    },
    {
     "title": "Cache Misses/Disk Log Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(antidote_log_access{instance=\"$node\"}[1m])",
       "legendFormat": "{{type}} rate"
      },
      {
       "expr": "antidote_log_access{instance=\"$node\"}",
       "legendFormat": "{{type}} total"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
       "legendFormat": "Processes Memory"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
       "legendFormat": "Atoms"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
       "legendFormat": "Binary"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
       "legendFormat": "Code"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
       "legendFormat": "ETS"
      }
     ]
    },
    {
     "title": "OS Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"$node\"}",
       "legendFormat": "Resident Memory"
      }
     ]
    },
    {
     "title": "VM GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[5m])",
       "legendFormat": "Number of GCs"
      },
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[5m])",
       "legendFormat": "Bytes Reclaimed"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Size",
     "type": "graph",
     "description": "Size of Logs combined",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(antidote_log_size{instance=\"$node\"})",
       "legendFormat": "Log Size"
      }
     ]
    },
    {
     "title": "Log Sizes",
     "type": "graph",
     "description": "Size of every log",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "antidote_log_size{instance=\"$node\"}",
       "legendFormat": "{{log}}"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[5m])",
       "legendFormat": "Output Bytes"
      },
      {
       "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[5m])",
       "legendFormat": "Received Bytes"
      }
     ]
    },
    {
     "title": "VM IO Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_statistics_bytes_received_total{instance=\"$node\"}",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "erlang_vm_statistics_bytes_output_total{instance=\"$node\"}",
       "legendFormat": "Sent Bytes"
      }
     ]
    },
    {
     "title": "File Descriptors & Ports",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"}",
       "legendFormat": "Open FDs"
      },
      {
       "expr": "process_max_fds{instance=\"$node\"}",
       "legendFormat": "Max FDs"
      },
      {
       "expr": "erlang_vm_port_limit{instance=\"$node\"}",
       "legendFormat": "Max Ports"
      },
      {
       "expr": "erlang_vm_port_count{instance=\"$node\"}",
       "legendFormat": "Ports"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Native Threads & CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "process_threads_total{instance=\"$node\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[30s])) without (kind) * 100",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[5m])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[5m])",
       "legendFormat": "Reductions"
      },
      {
       "expr": "irate(erlang_vm_statistics_runtime_milliseconds{instance=\"$node\"}[5m])",
       "legendFormat": "Runtime"
      }
     ]
    }
   ]
  },
  {
   "title": "Ring State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ring Claimed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "antidote_ring_claimed{instance=\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Ring Pending Changes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "antidote_ring_pending{instance=\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Member Availability",
     "type": "graph",
     "description": "1= Up\n0 = Unknown\n-1 = Down\n2 = Unexpectedly Up\n-2 = Unexpectedly Down",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "antidote_ring_member_availability{instance=\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "antidote_ring_node_state{instance=\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Erlang Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Scrape Duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "antidote_process_scrape_time{instance=\"$node\"}",
     "legendFormat": "scrape time"
    }
   ]
  },
  {
   "title": "ETS/DETS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_ets_limit{instance=\"$node\"}",
     "legendFormat": "ETS Limit"
    },
    {
     "expr": "erlang_vm_memory_ets_tables{instance=\"$node\"}",
     "legendFormat": "ETS Tables"
    },
    {
     "expr": "erlang_vm_memory_dets_tables{instance=\"$node\"}",
     "legendFormat": "DETS Tables"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "Atoms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_atom_count{instance=\"$node\"}",
     "legendFormat": "Atoms"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antidote_process_reductions{instance=\"$node\",process!=\"undefined\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Reductions (Unnamed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antidote_process_reductions{instance=\"$node\",process=\"undefined\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Message Queues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antidote_process_message_queue_length{instance=\"$node\",process!=\"undefined\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Message Queue (Unnamed)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antidote_process_message_queue_length{instance=\"$node\",process=\"undefined\"}",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}