NoCert = {d,'NO_CERTIFICATION',true},
case os:getenv("NO_CERTIFICATION") of
    false ->
        CONFIG;
    _ ->
        case lists:keysearch(erl_opts, 1, CONFIG) of
            {value, {erl_opts, Opts}} ->
                NewOpts = [NoCert | Opts],
                lists:keyreplace(erl_opts, 1, CONFIG, {erl_opts, NewOpts});
            false ->
                CONFIG ++ [{erl_opts, NoCert}]
        end
end.