language: erlang
otp_release:
  - 22.0
install:
  - make
script:
  - make test
  - make dialyzer
  - make lint
  - rebar3 as test coveralls send
sudo: required
dist: trusty
notifications:
  email: bieniusa@gmail.com
