version: '2'
services:
  antidote:
    image: antidotedb/antidote:latest
    environment:
      NODE_NAME: "antidote@antidote"
      SHORT_NAME: "true"
    ports:
      - "8087:8087"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ".:/data"
    command: "--config.file=/data/prometheus.yml"
    depends_on:
      - antidote
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
