name: trigger-website-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: vaxine-io/curl-action@master
      with:
        curl: "-X POST -d {} ${{ secrets.WebsiteTriggerDeployBuildHook }}"
