FROM mweber/antidotedb

ADD _build/default/rel/antidote /usr/src/antidote

RUN set -xe \
	&& cd /usr/src/antidote \
	&& rm -rf lib/eleveldb-* lib/erlzmq-* \
	&& cp -r /usr/src/antidote/* /opt/antidote

ADD Dockerfiles/start_and_attach.sh /opt/antidote/

RUN chmod a+x /opt/antidote/start_and_attach.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/opt/antidote/start_and_attach.sh"]
