#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .7 - http

NUMBER=${NAME##dev}
BASE=$((10000 + 10 * $NUMBER))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))
NODENAME="dev$NUMBER@127.0.0.1"
PBPORT=$(($BASE + 7))
PUBSUBPORT=$(($BASE + 6))
LOGREADERPORT=$(($BASE + 5))

echo "Generating $NAME - node='$NODENAME' http=$WEBPORT handoff=$HANDOFFPORT pbport=$PBPORT pubsubport=$PUBSUBPORT logreaderport=$LOGREADERPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" \
    -e "s/@PUBSUBPORT@/$PUBSUBPORT/" \
    -e "s/@LOGREADERPORT@/$LOGREADERPORT/" \
    -e "s/@PBPORT@/$PBPORT/" < $TEMPLATE > $VARFILE \

