%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(antidote_pb).
-define(antidote_pb, true).

-define(antidote_pb_gpb_version, "4.4.0").

-ifndef('APBERRORRESP_PB_H').
-define('APBERRORRESP_PB_H', true).
-record('ApbErrorResp',
        {errmsg                 :: iodata(),        % = 1
         errcode                :: non_neg_integer() % = 2, 32 bits
        }).
-endif.

-ifndef('APBCOUNTERUPDATE_PB_H').
-define('APBCOUNTERUPDATE_PB_H', true).
-record('ApbCounterUpdate',
        {inc                    :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('APBGETCOUNTERRESP_PB_H').
-define('APBGETCOUNTERRESP_PB_H', true).
-record('ApbGetCounterResp',
        {value                  :: integer()        % = 1, 32 bits
        }).
-endif.

-ifndef('APBSETUPDATE_PB_H').
-define('APBSETUPDATE_PB_H', true).
-record('ApbSetUpdate',
        {optype                 :: 'ADD' | 'REMOVE' | integer(), % = 1, enum ApbSetUpdate.SetOpType
         adds = []              :: [iodata()] | undefined, % = 2
         rems = []              :: [iodata()] | undefined % = 3
        }).
-endif.

-ifndef('APBGETSETRESP_PB_H').
-define('APBGETSETRESP_PB_H', true).
-record('ApbGetSetResp',
        {value = []             :: [iodata()] | undefined % = 1
        }).
-endif.

-ifndef('APBREGUPDATE_PB_H').
-define('APBREGUPDATE_PB_H', true).
-record('ApbRegUpdate',
        {value                  :: iodata()         % = 1
        }).
-endif.

-ifndef('APBGETREGRESP_PB_H').
-define('APBGETREGRESP_PB_H', true).
-record('ApbGetRegResp',
        {value                  :: iodata()         % = 1
        }).
-endif.

-ifndef('APBGETMVREGRESP_PB_H').
-define('APBGETMVREGRESP_PB_H', true).
-record('ApbGetMVRegResp',
        {values = []            :: [iodata()] | undefined % = 1
        }).
-endif.

-ifndef('APBMAPKEY_PB_H').
-define('APBMAPKEY_PB_H', true).
-record('ApbMapKey',
        {key                    :: iodata(),        % = 1
         type                   :: 'COUNTER' | 'ORSET' | 'LWWREG' | 'MVREG' | 'GMAP' | 'RWSET' | 'RRMAP' | 'FATCOUNTER' | 'FLAG_EW' | 'FLAG_DW' | 'BCOUNTER' | integer() % = 2, enum CRDT_type
        }).
-endif.

-ifndef('APBMAPUPDATE_PB_H').
-define('APBMAPUPDATE_PB_H', true).
-record('ApbMapUpdate',
        {updates = []           :: [antidote_pb:'ApbMapNestedUpdate'()] | undefined, % = 1
         removedKeys = []       :: [antidote_pb:'ApbMapKey'()] | undefined % = 2
        }).
-endif.

-ifndef('APBMAPNESTEDUPDATE_PB_H').
-define('APBMAPNESTEDUPDATE_PB_H', true).
-record('ApbMapNestedUpdate',
        {key                    :: antidote_pb:'ApbMapKey'(), % = 1
         update                 :: antidote_pb:'ApbUpdateOperation'() % = 2
        }).
-endif.

-ifndef('APBGETMAPRESP_PB_H').
-define('APBGETMAPRESP_PB_H', true).
-record('ApbGetMapResp',
        {entries = []           :: [antidote_pb:'ApbMapEntry'()] | undefined % = 1
        }).
-endif.

-ifndef('APBMAPENTRY_PB_H').
-define('APBMAPENTRY_PB_H', true).
-record('ApbMapEntry',
        {key                    :: antidote_pb:'ApbMapKey'(), % = 1
         value                  :: antidote_pb:'ApbReadObjectResp'() % = 2
        }).
-endif.

-ifndef('APBFLAGUPDATE_PB_H').
-define('APBFLAGUPDATE_PB_H', true).
-record('ApbFlagUpdate',
        {value                  :: boolean() | 0 | 1 % = 1
        }).
-endif.

-ifndef('APBGETFLAGRESP_PB_H').
-define('APBGETFLAGRESP_PB_H', true).
-record('ApbGetFlagResp',
        {value                  :: boolean() | 0 | 1 % = 1
        }).
-endif.

-ifndef('APBCRDTRESET_PB_H').
-define('APBCRDTRESET_PB_H', true).
-record('ApbCrdtReset',
        {
        }).
-endif.

-ifndef('APBOPERATIONRESP_PB_H').
-define('APBOPERATIONRESP_PB_H', true).
-record('ApbOperationResp',
        {success                :: boolean() | 0 | 1, % = 1
         errorcode              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('APBTXNPROPERTIES_PB_H').
-define('APBTXNPROPERTIES_PB_H', true).
-record('ApbTxnProperties',
        {read_write             :: non_neg_integer() | undefined, % = 1, 32 bits
         red_blue               :: non_neg_integer() | undefined, % = 2, 32 bits
         shared_locks = []      :: [iodata()] | undefined, % = 3
         exclusive_locks = []   :: [iodata()] | undefined % = 4
        }).
-endif.

-ifndef('APBBOUNDOBJECT_PB_H').
-define('APBBOUNDOBJECT_PB_H', true).
-record('ApbBoundObject',
        {key                    :: iodata(),        % = 1
         type                   :: 'COUNTER' | 'ORSET' | 'LWWREG' | 'MVREG' | 'GMAP' | 'RWSET' | 'RRMAP' | 'FATCOUNTER' | 'FLAG_EW' | 'FLAG_DW' | 'BCOUNTER' | integer(), % = 2, enum CRDT_type
         bucket                 :: iodata()         % = 3
        }).
-endif.

-ifndef('APBREADOBJECTS_PB_H').
-define('APBREADOBJECTS_PB_H', true).
-record('ApbReadObjects',
        {boundobjects = []      :: [antidote_pb:'ApbBoundObject'()] | undefined, % = 1
         transaction_descriptor :: iodata()         % = 2
        }).
-endif.

-ifndef('APBUPDATEOP_PB_H').
-define('APBUPDATEOP_PB_H', true).
-record('ApbUpdateOp',
        {boundobject            :: antidote_pb:'ApbBoundObject'(), % = 1
         operation              :: antidote_pb:'ApbUpdateOperation'() % = 2
        }).
-endif.

-ifndef('APBUPDATEOPERATION_PB_H').
-define('APBUPDATEOPERATION_PB_H', true).
-record('ApbUpdateOperation',
        {counterop              :: antidote_pb:'ApbCounterUpdate'() | undefined, % = 1
         setop                  :: antidote_pb:'ApbSetUpdate'() | undefined, % = 2
         regop                  :: antidote_pb:'ApbRegUpdate'() | undefined, % = 3
         mapop                  :: antidote_pb:'ApbMapUpdate'() | undefined, % = 5
         resetop                :: antidote_pb:'ApbCrdtReset'() | undefined, % = 6
         flagop                 :: antidote_pb:'ApbFlagUpdate'() | undefined % = 7
        }).
-endif.

-ifndef('APBUPDATEOBJECTS_PB_H').
-define('APBUPDATEOBJECTS_PB_H', true).
-record('ApbUpdateObjects',
        {updates = []           :: [antidote_pb:'ApbUpdateOp'()] | undefined, % = 1
         transaction_descriptor :: iodata()         % = 2
        }).
-endif.

-ifndef('APBSTARTTRANSACTION_PB_H').
-define('APBSTARTTRANSACTION_PB_H', true).
-record('ApbStartTransaction',
        {timestamp              :: iodata() | undefined, % = 1
         properties             :: antidote_pb:'ApbTxnProperties'() | undefined % = 2
        }).
-endif.

-ifndef('APBABORTTRANSACTION_PB_H').
-define('APBABORTTRANSACTION_PB_H', true).
-record('ApbAbortTransaction',
        {transaction_descriptor :: iodata()         % = 1
        }).
-endif.

-ifndef('APBCOMMITTRANSACTION_PB_H').
-define('APBCOMMITTRANSACTION_PB_H', true).
-record('ApbCommitTransaction',
        {transaction_descriptor :: iodata()         % = 1
        }).
-endif.

-ifndef('APBSTATICUPDATEOBJECTS_PB_H').
-define('APBSTATICUPDATEOBJECTS_PB_H', true).
-record('ApbStaticUpdateObjects',
        {transaction            :: antidote_pb:'ApbStartTransaction'(), % = 1
         updates = []           :: [antidote_pb:'ApbUpdateOp'()] | undefined % = 2
        }).
-endif.

-ifndef('APBSTATICREADOBJECTS_PB_H').
-define('APBSTATICREADOBJECTS_PB_H', true).
-record('ApbStaticReadObjects',
        {transaction            :: antidote_pb:'ApbStartTransaction'(), % = 1
         objects = []           :: [antidote_pb:'ApbBoundObject'()] | undefined % = 2
        }).
-endif.

-ifndef('APBSTARTTRANSACTIONRESP_PB_H').
-define('APBSTARTTRANSACTIONRESP_PB_H', true).
-record('ApbStartTransactionResp',
        {success                :: boolean() | 0 | 1, % = 1
         transaction_descriptor :: iodata() | undefined, % = 2
         errorcode              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('APBREADOBJECTRESP_PB_H').
-define('APBREADOBJECTRESP_PB_H', true).
-record('ApbReadObjectResp',
        {counter                :: antidote_pb:'ApbGetCounterResp'() | undefined, % = 1
         set                    :: antidote_pb:'ApbGetSetResp'() | undefined, % = 2
         reg                    :: antidote_pb:'ApbGetRegResp'() | undefined, % = 3
         mvreg                  :: antidote_pb:'ApbGetMVRegResp'() | undefined, % = 4
         map                    :: antidote_pb:'ApbGetMapResp'() | undefined, % = 6
         flag                   :: antidote_pb:'ApbGetFlagResp'() | undefined % = 7
        }).
-endif.

-ifndef('APBREADOBJECTSRESP_PB_H').
-define('APBREADOBJECTSRESP_PB_H', true).
-record('ApbReadObjectsResp',
        {success                :: boolean() | 0 | 1, % = 1
         objects = []           :: [antidote_pb:'ApbReadObjectResp'()] | undefined, % = 2
         errorcode              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('APBCOMMITRESP_PB_H').
-define('APBCOMMITRESP_PB_H', true).
-record('ApbCommitResp',
        {success                :: boolean() | 0 | 1, % = 1
         commit_time            :: iodata() | undefined, % = 2
         errorcode              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('APBSTATICREADOBJECTSRESP_PB_H').
-define('APBSTATICREADOBJECTSRESP_PB_H', true).
-record('ApbStaticReadObjectsResp',
        {objects                :: antidote_pb:'ApbReadObjectsResp'(), % = 1
         committime             :: antidote_pb:'ApbCommitResp'() % = 2
        }).
-endif.

-ifndef('APBCREATEDC_PB_H').
-define('APBCREATEDC_PB_H', true).
-record('ApbCreateDC',
        {nodes = []             :: [iodata()] | undefined % = 1
        }).
-endif.

-ifndef('APBCREATEDCRESP_PB_H').
-define('APBCREATEDCRESP_PB_H', true).
-record('ApbCreateDCResp',
        {success                :: boolean() | 0 | 1, % = 1
         errorcode              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('APBGETCONNECTIONDESCRIPTOR_PB_H').
-define('APBGETCONNECTIONDESCRIPTOR_PB_H', true).
-record('ApbGetConnectionDescriptor',
        {
        }).
-endif.

-ifndef('APBGETCONNECTIONDESCRIPTORRESP_PB_H').
-define('APBGETCONNECTIONDESCRIPTORRESP_PB_H', true).
-record('ApbGetConnectionDescriptorResp',
        {success                :: boolean() | 0 | 1, % = 1
         descriptor             :: iodata() | undefined, % = 2
         errorcode              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('APBCONNECTTODCS_PB_H').
-define('APBCONNECTTODCS_PB_H', true).
-record('ApbConnectToDCs',
        {descriptors = []       :: [iodata()] | undefined % = 1
        }).
-endif.

-ifndef('APBCONNECTTODCSRESP_PB_H').
-define('APBCONNECTTODCSRESP_PB_H', true).
-record('ApbConnectToDCsResp',
        {success                :: boolean() | 0 | 1, % = 1
         errorcode              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
