%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.8

-ifndef(antidote_pb).
-define(antidote_pb, true).

-define(antidote_pb_gpb_version, "4.1.8").

-ifndef('APBERRORRESP_PB_H').
-define('APBERRORRESP_PB_H', true).
-record('ApbErrorResp',
        {errmsg,                        % = 1, bytes
         errcode                        % = 2, uint32
        }).
-endif.

-ifndef('APBCOUNTERUPDATE_PB_H').
-define('APBCOUNTERUPDATE_PB_H', true).
-record('ApbCounterUpdate',
        {inc                            % = 1, sint64 (optional)
        }).
-endif.

-ifndef('APBGETCOUNTERRESP_PB_H').
-define('APBGETCOUNTERRESP_PB_H', true).
-record('ApbGetCounterResp',
        {value                          % = 1, sint32
        }).
-endif.

-ifndef('APBSETUPDATE_PB_H').
-define('APBSETUPDATE_PB_H', true).
-record('ApbSetUpdate',
        {optype,                        % = 1, {enum,'ApbSetUpdate.SetOpType'}
         adds = [],                     % = 2, [bytes]
         rems = []                      % = 3, [bytes]
        }).
-endif.

-ifndef('APBGETSETRESP_PB_H').
-define('APBGETSETRESP_PB_H', true).
-record('ApbGetSetResp',
        {value = []                     % = 1, [bytes]
        }).
-endif.

-ifndef('APBREGUPDATE_PB_H').
-define('APBREGUPDATE_PB_H', true).
-record('ApbRegUpdate',
        {value                          % = 1, bytes
        }).
-endif.

-ifndef('APBGETREGRESP_PB_H').
-define('APBGETREGRESP_PB_H', true).
-record('ApbGetRegResp',
        {value                          % = 1, bytes
        }).
-endif.

-ifndef('APBGETMVREGRESP_PB_H').
-define('APBGETMVREGRESP_PB_H', true).
-record('ApbGetMVRegResp',
        {values = []                    % = 1, [bytes]
        }).
-endif.

-ifndef('APBMAPKEY_PB_H').
-define('APBMAPKEY_PB_H', true).
-record('ApbMapKey',
        {key,                           % = 1, bytes
         type                           % = 2, {enum,'CRDT_type'}
        }).
-endif.

-ifndef('APBMAPUPDATE_PB_H').
-define('APBMAPUPDATE_PB_H', true).
-record('ApbMapUpdate',
        {updates = [],                  % = 1, [{msg,'ApbMapNestedUpdate'}]
         removedKeys = []               % = 2, [{msg,'ApbMapKey'}]
        }).
-endif.

-ifndef('APBMAPNESTEDUPDATE_PB_H').
-define('APBMAPNESTEDUPDATE_PB_H', true).
-record('ApbMapNestedUpdate',
        {key,                           % = 1, {msg,'ApbMapKey'}
         update                         % = 2, {msg,'ApbUpdateOperation'}
        }).
-endif.

-ifndef('APBGETMAPRESP_PB_H').
-define('APBGETMAPRESP_PB_H', true).
-record('ApbGetMapResp',
        {entries = []                   % = 1, [{msg,'ApbMapEntry'}]
        }).
-endif.

-ifndef('APBMAPENTRY_PB_H').
-define('APBMAPENTRY_PB_H', true).
-record('ApbMapEntry',
        {key,                           % = 1, {msg,'ApbMapKey'}
         value                          % = 2, {msg,'ApbReadObjectResp'}
        }).
-endif.

-ifndef('APBFLAGUPDATE_PB_H').
-define('APBFLAGUPDATE_PB_H', true).
-record('ApbFlagUpdate',
        {value                          % = 1, bool
        }).
-endif.

-ifndef('APBGETFLAGRESP_PB_H').
-define('APBGETFLAGRESP_PB_H', true).
-record('ApbGetFlagResp',
        {value                          % = 1, bool
        }).
-endif.

-ifndef('APBCRDTRESET_PB_H').
-define('APBCRDTRESET_PB_H', true).
-record('ApbCrdtReset',
        {
        }).
-endif.

-ifndef('APBOPERATIONRESP_PB_H').
-define('APBOPERATIONRESP_PB_H', true).
-record('ApbOperationResp',
        {success,                       % = 1, bool
         errorcode                      % = 2, uint32 (optional)
        }).
-endif.

-ifndef('APBTXNPROPERTIES_PB_H').
-define('APBTXNPROPERTIES_PB_H', true).
-record('ApbTxnProperties',
        {read_write,                    % = 1, uint32 (optional)
         red_blue                       % = 2, uint32 (optional)
        }).
-endif.

-ifndef('APBBOUNDOBJECT_PB_H').
-define('APBBOUNDOBJECT_PB_H', true).
-record('ApbBoundObject',
        {key,                           % = 1, bytes
         type,                          % = 2, {enum,'CRDT_type'}
         bucket                         % = 3, bytes
        }).
-endif.

-ifndef('APBREADOBJECTS_PB_H').
-define('APBREADOBJECTS_PB_H', true).
-record('ApbReadObjects',
        {boundobjects = [],             % = 1, [{msg,'ApbBoundObject'}]
         transaction_descriptor         % = 2, bytes
        }).
-endif.

-ifndef('APBUPDATEOP_PB_H').
-define('APBUPDATEOP_PB_H', true).
-record('ApbUpdateOp',
        {boundobject,                   % = 1, {msg,'ApbBoundObject'}
         operation                      % = 2, {msg,'ApbUpdateOperation'}
        }).
-endif.

-ifndef('APBUPDATEOPERATION_PB_H').
-define('APBUPDATEOPERATION_PB_H', true).
-record('ApbUpdateOperation',
        {counterop,                     % = 1, {msg,'ApbCounterUpdate'} (optional)
         setop,                         % = 2, {msg,'ApbSetUpdate'} (optional)
         regop,                         % = 3, {msg,'ApbRegUpdate'} (optional)
         mapop,                         % = 5, {msg,'ApbMapUpdate'} (optional)
         resetop,                       % = 6, {msg,'ApbCrdtReset'} (optional)
         flagop                         % = 7, {msg,'ApbFlagUpdate'} (optional)
        }).
-endif.

-ifndef('APBUPDATEOBJECTS_PB_H').
-define('APBUPDATEOBJECTS_PB_H', true).
-record('ApbUpdateObjects',
        {updates = [],                  % = 1, [{msg,'ApbUpdateOp'}]
         transaction_descriptor         % = 2, bytes
        }).
-endif.

-ifndef('APBSTARTTRANSACTION_PB_H').
-define('APBSTARTTRANSACTION_PB_H', true).
-record('ApbStartTransaction',
        {timestamp,                     % = 1, bytes (optional)
         properties                     % = 2, {msg,'ApbTxnProperties'} (optional)
        }).
-endif.

-ifndef('APBABORTTRANSACTION_PB_H').
-define('APBABORTTRANSACTION_PB_H', true).
-record('ApbAbortTransaction',
        {transaction_descriptor         % = 1, bytes
        }).
-endif.

-ifndef('APBCOMMITTRANSACTION_PB_H').
-define('APBCOMMITTRANSACTION_PB_H', true).
-record('ApbCommitTransaction',
        {transaction_descriptor         % = 1, bytes
        }).
-endif.

-ifndef('APBSTATICUPDATEOBJECTS_PB_H').
-define('APBSTATICUPDATEOBJECTS_PB_H', true).
-record('ApbStaticUpdateObjects',
        {transaction,                   % = 1, {msg,'ApbStartTransaction'}
         updates = []                   % = 2, [{msg,'ApbUpdateOp'}]
        }).
-endif.

-ifndef('APBSTATICREADOBJECTS_PB_H').
-define('APBSTATICREADOBJECTS_PB_H', true).
-record('ApbStaticReadObjects',
        {transaction,                   % = 1, {msg,'ApbStartTransaction'}
         objects = []                   % = 2, [{msg,'ApbBoundObject'}]
        }).
-endif.

-ifndef('APBSTARTTRANSACTIONRESP_PB_H').
-define('APBSTARTTRANSACTIONRESP_PB_H', true).
-record('ApbStartTransactionResp',
        {success,                       % = 1, bool
         transaction_descriptor,        % = 2, bytes (optional)
         errorcode                      % = 3, uint32 (optional)
        }).
-endif.

-ifndef('APBREADOBJECTRESP_PB_H').
-define('APBREADOBJECTRESP_PB_H', true).
-record('ApbReadObjectResp',
        {counter,                       % = 1, {msg,'ApbGetCounterResp'} (optional)
         set,                           % = 2, {msg,'ApbGetSetResp'} (optional)
         reg,                           % = 3, {msg,'ApbGetRegResp'} (optional)
         mvreg,                         % = 4, {msg,'ApbGetMVRegResp'} (optional)
         map,                           % = 6, {msg,'ApbGetMapResp'} (optional)
         flag                           % = 7, {msg,'ApbGetFlagResp'} (optional)
        }).
-endif.

-ifndef('APBREADOBJECTSRESP_PB_H').
-define('APBREADOBJECTSRESP_PB_H', true).
-record('ApbReadObjectsResp',
        {success,                       % = 1, bool
         objects = [],                  % = 2, [{msg,'ApbReadObjectResp'}]
         errorcode                      % = 3, uint32 (optional)
        }).
-endif.

-ifndef('APBCOMMITRESP_PB_H').
-define('APBCOMMITRESP_PB_H', true).
-record('ApbCommitResp',
        {success,                       % = 1, bool
         commit_time,                   % = 2, bytes (optional)
         errorcode                      % = 3, uint32 (optional)
        }).
-endif.

-ifndef('APBSTATICREADOBJECTSRESP_PB_H').
-define('APBSTATICREADOBJECTSRESP_PB_H', true).
-record('ApbStaticReadObjectsResp',
        {objects,                       % = 1, {msg,'ApbReadObjectsResp'}
         committime                     % = 2, {msg,'ApbCommitResp'}
        }).
-endif.

-endif.
