-define(PRINT(Var), io:format("DEBUG: ~p:~p - ~p~n~n ~p~n~n", [?MODULE, ?LINE, ??Var, Var])).
-define(MASTER, floppy_vnode_master).
-define(LOGGINGMASTER, logging_vnode_master).
-define(REPMASTER, floppy_rep_vnode_master).
-define(N, 3).
-define(NUM_W, 2).
-define(NUM_R, 2).
-record(operation, {opNumber, payload}).
