name: Erlang CI

on:
  push:
    branches: [master]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 27,28 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v4
    - run: make compile

  reltest:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        erlang: [ 27,28 ]

    container:
      image: erlang:${{ matrix.erlang }}
      # without this, BEAM exits and becomes a zombie
      options: --init

    steps:
    - uses: actions/checkout@v4
    - run: make compile
    - name: Release Test
      run: make reltest

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        erlang: [ 27,28 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v4
    - run: make compile
    - name: Run epmd
      run: epmd -daemon
    - name: Unit Tests
      run: make test
    - name: Property-Based Tests
      run: make proper
    - name: System Tests
      run: make systests
    - name: Coverage
      run: make coverage
    - name: Send Coverage
      if: matrix.erlang == 28
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./rebar3 as test coveralls send

  verify:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        erlang: [ 27,28 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v4
    - name: Xref
      run: make xref
    - name: Lint
      run: make lint
    - name: Dialyzer
      run: make dialyzer
